/*
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.test.minijava.parser.antlr.internal.InternalMinijavaParser;
import org.xtext.test.minijava.services.MinijavaGrammarAccess;

public class MinijavaParser extends AbstractAntlrParser {

	@Inject
	private MinijavaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMinijavaParser createParser(XtextTokenStream stream) {
		return new InternalMinijavaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Goal";
	}

	public MinijavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MinijavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
