/*
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MinijavaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/test/minijava/parser/antlr/internal/InternalMinijava.tokens");
	}
}
