/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.test.minijava.minijava.MinijavaPackage;
import org.xtext.test.minijava.minijava.SquareBrackets;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Square Brackets</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SquareBracketsImpl extends ExprImpl implements SquareBrackets
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SquareBracketsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MinijavaPackage.Literals.SQUARE_BRACKETS;
  }

} //SquareBracketsImpl
