/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.test.minijava.minijava.MinijavaPackage;
import org.xtext.test.minijava.minijava.VarLi;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Var Li</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VarLiImpl extends MinimalEObjectImpl.Container implements VarLi
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarLiImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MinijavaPackage.Literals.VAR_LI;
  }

} //VarLiImpl
