/*
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMinijavaScopeProvider extends DelegatingScopeProvider {
}
