/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Addition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.test.minijava.minijava.MinijavaPackage#getAddition()
 * @model
 * @generated
 */
public interface Addition extends Expr
{
} // Addition
