/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.test.minijava.minijava.MainClass#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.MainClass#getVarDeclarations <em>Var Declarations</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.MainClass#getMethodDeclarations <em>Method Declarations</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.MainClass#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMainClass()
 * @model
 * @generated
 */
public interface MainClass extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMainClass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.MainClass#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Var Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.test.minijava.minijava.VarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Declarations</em>' containment reference list.
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMainClass_VarDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<VarDeclaration> getVarDeclarations();

  /**
   * Returns the value of the '<em><b>Method Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.test.minijava.minijava.Method}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Declarations</em>' containment reference list.
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMainClass_MethodDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<Method> getMethodDeclarations();

  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference.
   * @see #setStatement(Statement)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMainClass_Statement()
   * @model containment="true"
   * @generated
   */
  Statement getStatement();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.MainClass#getStatement <em>Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' containment reference.
   * @see #getStatement()
   * @generated
   */
  void setStatement(Statement value);

} // MainClass
