/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.test.minijava.minijava.Method#getMethodType <em>Method Type</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Method#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Method#getVarList <em>Var List</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Method#getLocalVarDeclarations <em>Local Var Declarations</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Method#getStatements <em>Statements</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Method#getReturnExpression <em>Return Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMethod()
 * @model
 * @generated
 */
public interface Method extends EObject
{
  /**
   * Returns the value of the '<em><b>Method Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Type</em>' containment reference.
   * @see #setMethodType(Type)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMethod_MethodType()
   * @model containment="true"
   * @generated
   */
  Type getMethodType();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Method#getMethodType <em>Method Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method Type</em>' containment reference.
   * @see #getMethodType()
   * @generated
   */
  void setMethodType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMethod_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Method#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Var List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var List</em>' containment reference.
   * @see #setVarList(VarList)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMethod_VarList()
   * @model containment="true"
   * @generated
   */
  VarList getVarList();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Method#getVarList <em>Var List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var List</em>' containment reference.
   * @see #getVarList()
   * @generated
   */
  void setVarList(VarList value);

  /**
   * Returns the value of the '<em><b>Local Var Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.test.minijava.minijava.VarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local Var Declarations</em>' containment reference list.
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMethod_LocalVarDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<VarDeclaration> getLocalVarDeclarations();

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.test.minijava.minijava.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMethod_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

  /**
   * Returns the value of the '<em><b>Return Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Expression</em>' containment reference.
   * @see #setReturnExpression(Expr)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getMethod_ReturnExpression()
   * @model containment="true"
   * @generated
   */
  Expr getReturnExpression();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Method#getReturnExpression <em>Return Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Expression</em>' containment reference.
   * @see #getReturnExpression()
   * @generated
   */
  void setReturnExpression(Expr value);

} // Method
