/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Point</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.test.minijava.minijava.MinijavaPackage#getPoint()
 * @model
 * @generated
 */
public interface Point extends Expr
{
} // Point
