/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.test.minijava.minijava.Statement#getStatementType <em>Statement Type</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Statement#getStatements <em>Statements</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Statement#getFirstExpression <em>First Expression</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Statement#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Statement#isIsArrayElementAssignment <em>Is Array Element Assignment</em>}</li>
 *   <li>{@link org.xtext.test.minijava.minijava.Statement#getSecondExpression <em>Second Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.test.minijava.minijava.MinijavaPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Statement Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement Type</em>' attribute.
   * @see #setStatementType(String)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getStatement_StatementType()
   * @model
   * @generated
   */
  String getStatementType();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Statement#getStatementType <em>Statement Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement Type</em>' attribute.
   * @see #getStatementType()
   * @generated
   */
  void setStatementType(String value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.test.minijava.minijava.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getStatement_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

  /**
   * Returns the value of the '<em><b>First Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Expression</em>' containment reference.
   * @see #setFirstExpression(Expr)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getStatement_FirstExpression()
   * @model containment="true"
   * @generated
   */
  Expr getFirstExpression();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Statement#getFirstExpression <em>First Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Expression</em>' containment reference.
   * @see #getFirstExpression()
   * @generated
   */
  void setFirstExpression(Expr value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(Variable)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getStatement_Variable()
   * @model
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Statement#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Is Array Element Assignment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Array Element Assignment</em>' attribute.
   * @see #setIsArrayElementAssignment(boolean)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getStatement_IsArrayElementAssignment()
   * @model
   * @generated
   */
  boolean isIsArrayElementAssignment();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Statement#isIsArrayElementAssignment <em>Is Array Element Assignment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Array Element Assignment</em>' attribute.
   * @see #isIsArrayElementAssignment()
   * @generated
   */
  void setIsArrayElementAssignment(boolean value);

  /**
   * Returns the value of the '<em><b>Second Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second Expression</em>' containment reference.
   * @see #setSecondExpression(Expr)
   * @see org.xtext.test.minijava.minijava.MinijavaPackage#getStatement_SecondExpression()
   * @model containment="true"
   * @generated
   */
  Expr getSecondExpression();

  /**
   * Sets the value of the '{@link org.xtext.test.minijava.minijava.Statement#getSecondExpression <em>Second Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second Expression</em>' containment reference.
   * @see #getSecondExpression()
   * @generated
   */
  void setSecondExpression(Expr value);

} // Statement
