/**
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.minijava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var List</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.test.minijava.minijava.MinijavaPackage#getVarList()
 * @model
 * @generated
 */
public interface VarList extends EObject
{
} // VarList
