/*
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.test.minijava.ui.internal.MinijavaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MinijavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MinijavaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MinijavaActivator activator = MinijavaActivator.getInstance();
		return activator != null ? activator.getInjector(MinijavaActivator.ORG_XTEXT_TEST_MINIJAVA_MINIJAVA) : null;
	}

}
