/*
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.test.minijava.ui.internal.MinijavaActivator;

public class MinijavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MinijavaActivator.getInstance().getInjector("org.xtext.test.minijava.Minijava");
	}

}
