/*
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MinijavaUiModule extends AbstractMinijavaUiModule {

	public MinijavaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
