/*
 * generated by Xtext 2.25.0
 */
package org.xtext.test.minijava.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.test.minijava.MinijavaRuntimeModule;
import org.xtext.test.minijava.MinijavaStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MinijavaIdeSetup extends MinijavaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MinijavaRuntimeModule(), new MinijavaIdeModule()));
	}
	
}
